### ISSUE TITLE
Road to Serum v2

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#98]
The following tasks may introduce many breaking changes, so the next version will be 2.x when these are completed. 🚀

- [x] More detailed error objects

- [ ] Serum Development Kit (#97)

- [x] Revise the specification of `Serum.Plugin` and `Serum.Theme` behaviours.

- [ ] New Serum Development Server (#96)

- [ ] ~Module-based Project Configuration Format~

  ~Make `serum.exs` look like `mix.exs`, to make more organized and more extensible configuration format.~

- [x] `Serum.Post`, `Serum.Page` Improvements (#106)

- [ ] Allow specification of multiple authors (#114)

- And much more (maybe)
